name: Run tests

on:
  - pull_request
  - push

jobs:
  ci:
    uses: houseabsolute/workflow-perl-dzil-ci/.github/workflows/ci.yml@v0
    with:
      dist: Courriel
      ref: v0
      # File::LibMagic is a develop dep and needs the libmagic headers to
      # build.
      apt-packages-for-author-tests: libmagic-dev
